const menu = [
  {name:'Coffee',image:'assets/coffee.jpeg',items:[['Signature Latte','$4.80','Smooth espresso with fresh milk and a light layer of foam.'],['Flat White','$4.50','Double espresso with velvety steamed milk for a stronger coffee taste.'],['Cappuccino','$4.50','Espresso with steamed milk and a generous layer of milk foam.'],['Americano','$3.80','Espresso topped with hot water for a clean, full-bodied cup.'],['Mocha','$5.20','Espresso, chocolate and fresh milk topped with light foam.'],['Iced Kopi Latte','$4.90','A local-inspired iced coffee with espresso, milk and a touch of sweetness.']]},
  {name:'Non-Coffee',image:'assets/non-coffee.jpeg',items:[['Honey Lemon Cooler','$4.50','Fresh lemon and honey served chilled for a bright, refreshing drink.'],['Matcha Latte','$5.20','Smooth Japanese-style matcha blended with fresh milk.'],['Chocolate Milk','$4.80','Rich cocoa blended with fresh milk, served hot or iced.'],['Peach Iced Tea','$4.20','Light black tea with peach flavour, served over ice.'],['Fresh Lemon Tea','$4.20','Brewed tea with fresh lemon for a simple citrus finish.'],['Strawberry Milk','$4.80','Creamy chilled milk blended with strawberry flavour.']]},
  {name:'Breakfast',image:'assets/breakfast.jpeg',items:[['Kaya Butter Toast Set','$6.90','Crisp kaya butter toast with two soft-boiled eggs and hot coffee or tea.'],['Scrambled Egg Croissant','$7.50','Buttery croissant filled with soft scrambled eggs.'],['Ham & Cheese Toastie','$7.90','Toasted bread with sliced ham and melted cheese.'],['Peanut Butter Banana Toast','$6.50','Toast with peanut butter, sliced banana and a light honey drizzle.'],['Breakfast Egg Muffin','$7.20','English muffin with egg, cheese and chicken ham.'],['Granola Yoghurt Bowl','$6.90','Creamy yoghurt with crunchy granola and seasonal fruit.']]},
  {name:'All-Day Meal',image:'assets/all-day-meal.jpeg',items:[['Grilled Chicken Sourdough','$10.90','Grilled chicken, lettuce, tomato and house dressing in toasted sourdough.'],['Tuna Melt Sandwich','$9.90','Tuna filling with melted cheese on toasted bread, served with a small salad.'],['Mushroom Aglio Olio','$11.90','Spaghetti tossed with garlic, olive oil, chilli and sauteed mushrooms.'],['Creamy Chicken Pasta','$12.90','Pasta with grilled chicken in a mild creamy sauce.'],['Chicken Teriyaki Rice Bowl','$11.90','Steamed rice topped with teriyaki chicken and simple vegetables.'],['First Cafe Club Sandwich','$12.50','Triple-layer sandwich with chicken, egg, lettuce and tomato, served with fries.']]},
  {name:'Dessert',image:'assets/dessert.jpeg',items:[['Burnt Cheesecake Slice','$6.50','Creamy burnt cheesecake with a caramelised top and soft centre.'],['Chocolate Brownie','$5.50','Rich chocolate brownie with a soft centre and slightly crisp top.'],['Banana Walnut Cake','$5.80','Moist banana cake with walnuts and a light cinnamon aroma.'],['Tiramisu Cup','$6.80','Coffee-soaked sponge layered with smooth mascarpone cream.'],['Lemon Tart','$6.20','Buttery tart shell filled with bright, tangy lemon curd.'],['Vanilla Ice Cream Waffle','$8.90','Warm waffle served with vanilla ice cream and a light chocolate drizzle.']]}
];
const tabs=document.querySelector('.menu-tabs'), content=document.querySelector('.menu-content');
function renderMenu(index){const category=menu[index];tabs.innerHTML=menu.map((c,i)=>`<button role="tab" aria-selected="${i===index}" data-index="${i}">${c.name}</button>`).join('');content.innerHTML=`<div class="menu-feature"><div class="menu-feature-image"><img src="${category.image}" alt="${category.name} at First Cafe"><span>${category.name}</span></div><div class="menu-list">${category.items.map(([name,price,description])=>`<article class="menu-item"><div class="menu-item-top"><h3>${name}</h3><strong>${price}</strong></div><p>${description}</p></article>`).join('')}</div></div>`;tabs.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>renderMenu(+button.dataset.index)))}renderMenu(0);
const toggle=document.querySelector('.menu-toggle'), nav=document.querySelector('nav');toggle.addEventListener('click',()=>{const isOpen=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',isOpen);toggle.setAttribute('aria-label',isOpen?'Close navigation':'Open navigation')});nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')}));
document.querySelector('.contact-form').addEventListener('submit',event=>{event.preventDefault();event.currentTarget.querySelector('.form-status').textContent='Thank you — your message has been noted.';event.currentTarget.reset()});document.getElementById('year').textContent=new Date().getFullYear();
